theme: minima
title: Shawn Hamel
description: Operations & Strategy Leader

header_pages:
  - about.md
  - projects.md
  - contact.md

#social usernames
linkedin_username: shawnhamel
github_username: shhhamel19
